<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\StyleSheet.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\StyleSheet.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreHero.ToastNotification" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\7Colors\Business\Business.csproj" />
    <ProjectReference Include="..\..\7Colors\Core\Core.csproj" />
    <ProjectReference Include="..\..\7Colors\Data\Data.csproj" />
  </ItemGroup>

</Project>
